- README.md
- lib/index.js
- src/helpers.js
- src/index.js
- src/index.test.js
The MSYS2 project just added support for `tmate`; Might just as well use
it (especially because the reason `tmate` was added was to support
`action-tmate`).
See https://github.com/msys2/MSYS2-packages/pull/2211 for details about
MSYS2 adding support for `tmate`.
Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>
Original PR: #26
> Support Windows via MSYS2

- README.md
As @mxschmitt pointed out in #32 GitHub Actions has [existing config to timeout a step](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes).
Adding a section to the README to help user's discover this.
Closes #20. Replaced #32.
> Update docs on timeout

- lib/index.js
- src/helpers.js
- src/index.js
- src/index.test.js
I noticed while using this action that upon `touch continue`, you receive in the action console the following message:
```
Existing debugging session because '/continue' file was created
```
Which appears to have meant to read:
```
Exiting debugging session because '/continue' file was created
```
When I looked into the source code to fix this typo, I came across 5 or so separate instances of this misspelled string, leading me to believe this is the result of an inadvertent copy/paste.
I added `exitDebugSessionMessage` to `src/helpers.js` to both correct the typo, and to prevent future misspellings or inconsistencies if this message is ever refactored.
---
All existing tests were re-run and verified to be passing prior to the creation of this PR.
> replace multiple identical typos with a shared const string

- README.md
- action.yml
- lib/index.js
- package-lock.json
- package.json
- src/index.js
- src/index.test.js
With this commit, users can specify `limit-access-to-actor: true` in their workflow, which will ask the Action to install the public SSH key(s) [registered with the GitHub profile](https://docs.github.com/en/github/.authenticating-to-github/adding-a-new-ssh-key-to-your-github-account) of the GitHub user who triggered the workflow.
This is useful to restrict access e.g. when a GitHub workflow has to work with secrets such as code-signing certificates.
This addresses https://github.com/mxschmitt/action-tmate/issues/2
> Allow restricting access via public SSH keys registered with the GitHub profile

- lib/index.js
- src/index.js
When using `limit-access-to-actor` the web shell is not persistent. With this change, we only print it when its there.
Fixes #44
> fix: only print web shell when persistent

- lib/index.js
- src/index.js
I stumbled across this during a debugging session: when I quit the shell inside the `tmate` session, the SSH session went with it, too, and I could no longer connect. Yet the Action still was running, waiting for a `continue` file to be created.
Let's just treat the absence of a `tmate` session the same as the presence of that `continue` file: the user wants the workflow to move on.
> Also continue when the tmate socket was deleted

- README.md
I discovered this function yesterday and I think it complements your action nicely.
From the [docs](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#failure):
the following snippet makes a step run only if one of the previous steps has failed.
```
steps:
...
- name: The job has failed
if: ${{ failure() }}
```
> README: add example using failure()

- lib/index.js
- src/index.js
- src/index.test.js
Fixed two potential issues:
a) on self-hosted runners when the tmp directory does not get cleaned up
the tmate executable stays there, we fix this by removing if it exists
to ensure we have the latest version.
#59
b) We cleanup the tmate release tar after we extracted it
> fix: remove tmate executable if already exists

- lib/index.js
- src/index.js
- src/index.test.js
When `errexit` is turned on (e.g. via `set -e` in the Bash profile), even a simple typo will take the entire shell session with it. Usually, it is not set (except on macOS), but the `setup-miniconda` Action seems to append it to the Bash profile, probably assuming that it won't hurt because nobody is running GitHub workflows interactively (except we do, with `action-tmate`...).
That's not what we want, therefore let's turn it off specifically.
This fixes https://github.com/mxschmitt/action-tmate/issues/37.
> Turn `errexit` off in the shell sessions

- lib/index.js
- src/index.js
This was a regression introduced in #64 which broke the limit-access-to-actor functionality.
The order of the input parameters seems important, since first the parameters from tmate come and then from tmux.
Fixes #65
tested with:
```
name: CI
on: [push]
jobs:
test:
runs-on: ubuntu-latest
name: test
steps:
- uses: actions/checkout@v2
- name: Setup tmate session
uses: mxschmitt/action-tmate@bugfix/limit-access-to-actor
with:
limit-access-to-actor: true
```
> fix: limit-access-to-actor functionality

- .github/workflows/manual-test.yml
- lib/index.js
- src/index.js
D'oh! In my recent workaround, I totally forgot that on Windows, `/tmp` is not equal to `/tmp`...
This fixes that, and it also adds a (manual) workflow that can be used for interactive testing.
This fixes https://github.com/mxschmitt/action-tmate/issues/67
> Fix for VS2019

- README.md
Updating the `README` to add an example of how to manually trigger a debug build, without having to
add/remove or uncomment config and push commits each time.
Uses [`workflow_dispatch`][1] and [conditional steps][2].
[1]: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
[2]: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
> docs: add manually triggered debug example

- README.md
As I noted in [this][1] comment on #78, the formatting on the [Jekyll generated page][2] is wrong as
(I think) it's interpreting the `${{ ... }}` as a Liquid tag.
We need to wrap the code block in a [`{% raw %} .. {% endraw %}`][3], but the only way I could think
of doing this without it being visible in the GitHub markdown was to enclose it in a standard HTML
comment. Hacky, but seems to work!
[1]: https://github.com/mxschmitt/action-tmate/pull/78#issuecomment-821243039
[2]: https://mxschmitt.github.io/action-tmate/
[3]: https://blog.slaks.net/2013-06-10/jekyll-endraw-in-code/
> Fix Jekyll formatting of code block

- README.md
- action.yml
- lib/index.js
- src/helpers.js
- src/index.js
Hi, I found this action works very well! Thank you for creating this! 😊
Now, `action-tmate` only supports using `ssh.tmate.io`.
This change adds inputs about using other tmate servers.
I referred "Host your own tmate servers" in https://tmate.io/.
> Support user own tmate server

- lib/index.js
- src/helpers.js
- src/index.js
hi, thank you for creating action-tmate! I really love its DX :+1:
thie PR will add support for `alpine linux`, which does not have `apt-get`. 
I added codes to detect linux distro via `/etc/os-release` and use `apk` if distro seems to be alpine.
this already runs fine on my github action, like https://github.com/suntomi/deplo/runs/4402074337?check_suite_focus=true#step:7:26
regards,
> alpine linux support

- README.md
- action.yml
- lib/index.js
- src/index.js
- src/index.test.js
This is copy of #77 and modified according to #77 comments.
In some situations, `apt-get` can't be called without sudo, but sudo is not permitted to user. 
So, skipping dependency installation is necessary in this situation.
> add option to skip dependency installation [#77 reopen]

- action.yml
- lib/index.js
- src/helpers.js
- src/index.js
- src/index.test.js
Don't throw an exception if they match the expected form but rather if
they do _not_ match it.
Also add colon to the list of allowed characters as it must be used in
the fingerprints (which have the form of "SHA256:xxxxxx").
----
Sorry if I'm missing something obvious here, but it seems that the check can't work as currently written: as soon as I add
```yaml
with:
tmate-server-host: shell.example.com
```
to my work workflow, I get
```
Error: Invalid value for 'tmate-server-host': 'shell.example.com'
```
and looking at the code it seems impossible to avoid this.
I believe that the intention was to negate this check, but even then it's still not quite right because we also need to allow colons here. But, again, perhaps I'm misunderstanding something here because I just don't see how could …
> Fix checking validity of tmate-server-xxx parameters

- lib/index.js
- src/helpers.js
- src/index.js
Fixes https://github.com/mxschmitt/action-tmate/issues/108
> fix: validation of input parameters

- lib/index.js
- src/index.js
- src/index.test.js
To avoid having any more problems like the one from #105, I've changed the mock function in the tests return empty string rather than `undefined` when the option is not defined, to be consistent with the real function and added a new test checking that everything works without any options being set.
I've also made 2 other cosmetic changes that could be [not] applied independently of the 2 other ones to make test output nicer to read.
Sorry again for the breakage!
> Some tests improvements

- action.yml
- lib/index.js
- package-lock.json
- package.json
Node 12 has an end of life on April 30, 2022.
This PR updates the default runtime to [node16](https://github.blog/changelog/2021-12-10-github-actions-github-hosted-runners-now-run-node-js-16-by-default/), rather then node12.
This is supported on all Actions Runners v2.285.0 or later.
> runtime: upgrade nodejs runtime from v12 to v16

- .github/workflows/manual-test.yml
Follow up PR to #134 
I had to use a different job because AFAIK github actions doesn't support an optional container (I can't put an empty string as container image)
> Test containers in manual test matrix

- .github/workflows/manual-test.yml
- action.yml
- lib/index.js
- src/helpers.js
- src/index.js
Fix #135 
Note : I would like you to merge #137 first, so I can modify the container test matrix in this PR
> detect if sudo should be used

- .github/workflows/checkin.yml
- .github/workflows/manual-test.yml
- README.md
- update actions to latest
- update to use latest LTS nodejs for the PR test
- add macos-12.0 and windows-2022
- remove deprecated runners, macos-10.15 and ubuntu-18.04
> workflows: update action deps and runners

- action.yml
- lib/index.js
- src/helpers.js
- src/index.js
There was a recent uptick of probems with symptoms like this:
> Error: API rate limit exceeded for 172.176.196.48. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
Let's follow that advice and use authenticated REST API requests.
> Avoid exceeding the GitHub REST API rate limit

- lib/index.js
- src/index.js
- src/index.test.js
Due to [dependency issues](https://hackernoon.com/heres-what-dependency-hell-looks-like-and-how-to-avoid-it-tldr-libraries-may-be-causing-dependency-u87p33vn), it is currently a bit tricky to install the latest version of the `tmate` package on in MSYS2 on GitHub's hosted build agents.
The symptom of the current (incorrect) method is that we're running into "Error 127" which means that either an executable or a DLL was not found.
To install the latest version of the `tmate` package correctly, we would have to do a full upgrade of all installed MSYS2 packages, which would require us to parse the output of the `pacman -Syu` run to figure out whether system packages were upgraded, in which case a second `pacman -Su` invocation would be required.
Instead, let's go the simpler route and avoid …
> Fix action-tmate on Windows

- lib/index.js
- src/index.js
This allows this action to work with GHES instance whose api url is not the public github.com domain.
> Add support for using action with Github Enterprise server

- README.md
- action.yml
- lib/index.js
- src/index.js
This PR intends to implement a less heavy-handed solution than suggested in https://github.com/mxschmitt/action-tmate/issues/124: Instead of changing the default of `limit-access-to-actor` to `true`, it introduces a new `auto` mode and makes that the new default. This mode will look for public SSH keys in the actor's GitHub profile, and use them if found, otherwise warn and continue without public key authentication.
> Default to using public key authentication (if any public SSH key is registered)

- .github/workflows/manual-detached-test.yml
- README.md
- action.yml
- lib/index.js
- src/helpers.js
- src/index.js
In #131, first, and then in #156, a change was proposed to support the same functionality as CircleCI, where a terminal is open concurrent to the running job's steps. And as I [mentioned in the latter PR](https://github.com/mxschmitt/action-tmate/pull/156#issuecomment-1550984902), I have found that feature quite useful (implementing it "manually", by having two `shell: bash` steps).
Here is a very small PR to propose a much simpler UI but essentially offer the same feature: by setting the input `detached: true`, the `action-tmate` step will start a new, detached `tmate` session, print the information how to connect to that, and then continue with the workflow job's next steps, keeping the `tmate` session running. In the post-job phase, `action-tmate` will then wait for the session to end …
> Add support for a "detached" mode

- README.md
Similar to change proposed in #79.
Another possibility is to drop `${{ ... }}` and simply use `if: <expr>`, since
> GitHub Actions automatically evaluates the `if` conditional as an expression.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif
---
Before (https://mxschmitt.github.io/action-tmate/)
After (https://muzimuzhi.github.io/action-tmate/, temp)
> docs: fix Jekyll formatting of another code block

- .github/workflows/manual-detached-test.yml
- action.yml
- lib/index.js
- src/index.js
It would be nice to be able to configure the connection timeout separately from the action's overall timeout length. As far as I know, this is currently not possible (issue #133)
I've added a new optional parameter `connection-timeout` that accepts the number of seconds to wait for a connection at maximum. This value is defaulted to 600, which is what the previous fixed value was.
> Feat: Connect Timeout

- .github/workflows/checkin.yml
- .github/workflows/manual-detached-test.yml
- .github/workflows/manual-test.yml
- README.md
https://github.com/actions/checkout/releases/tag/v4.0.0
> chore(deps): bump to use actions/checkout v4 (node20 runtime)

- README.md
- action.yml
- lib/index.js
- src/helpers.js
- src/index.js
add new msys2-location input and use instead of hardcoding c:\msys64
Fixes #86
> add new input msys2-location

- .github/workflows/manual-detached-test.yml
- README.md
- detached/action.yml
I find myself _only_ using the detached mode as of the past year or so. Naturally, in hindsight I wish for that mode to be the default, for that reason. It would be far from a good idea to change the default _now_, after many years of users having grown accustomed to the current working of the Action.
But there's an easy way to have what I want anyway: by adding a "sub-Action", i.e. a sub-directory with an `action.yml` file that differs only in the default of the `detached` input parameter. That way, I can now use the following in my workflows and get precisely what I want:
```yml
- uses: mxschmitt/action-tmate/detached@v3
```
I imagine that this will be useful for other users, too, therefore I updated the `README.md` file accordingly.
> Add a "sub-Action" for the detached mode by default

- .github/workflows/manual-test.yml
It has gone to the ~Google~GitHub Graveyard.
> ci(manual-test): stop mentioning the obsolete ubuntu-20.04 pool

- README.md
- action.yml
- detached/action.yml
- lib/index.js
- src/index.js
In complex corporate setups, it is not uncommon that CI processes are designed to notify engineers at strategic times during lengthy workflows. To integrate `action-tmate` in such a process, it is necessary to have vital information (such as the SSH address) at hand, to be able to, say, send a Slack message to the person who will most likely want to connect to the tmate session. This PR adds support for that, by providing said information via Action outputs.
> Add support for the ssh commands in output

- .github/workflows/checkin.yml
- detached/action.yml
- package.json
In https://github.com/mxschmitt/action-tmate/pull/218, I added a convenient way to launch this Action in detached mode: `mxschmitt/action-tmate/detached@v3`.
The way this is implemented is a copy/edited version of `action.yml` in the `detached/` subdirectory.
This runs the danger of inadvertent divergences, as happened in https://github.com/mxschmitt/action-tmate/pull/221 (which I caught in time and the contributor gracefully addressed).
Let's add automation not only to update the file easily but also to cause a failure in the PR build with a helpful message suggesting how to fix the problem.
> ci: verify that the `action.yml` files are in sync

- .github/workflows/manual-test.yml
See https://github.com/actions/runner-images/blob/310e8e963731084df01bcbdbd5044a5ca7fc0c88/README.md#available-images.
Inspired by https://github.com/mxschmitt/action-tmate/pull/220.
> ci(manual-test): update list of runner images

- .github/workflows/manual-test.yml
- .github/workflows/update-manual-test.js
As I realized in https://github.com/mxschmitt/action-tmate/pull/224#issuecomment-2846405397, the `manual-test` workflow, which is currently set up as a matrix job that runs one job for every available runner OS (and then a couple more Docker containers), is not very useful as-is. Nobody logs into a dozen tmate sessions concurrently to do anything reasonable.
What is typically needed is a single runner OS, or Docker container.
So let's switch this to a workflow where the user specified via `workflow_dispatch` input what exactly they want to run.
While at it, add a script to update the list of available runner images by scraping the official `runner-images` README. I considered adding a scheduled GitHub workflow to update this on a regular basis, but unfortunately `git push` is not …
> Convert the `manual-test` workflow to allow specifying which runner OS to use
